// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2r7IGSY6FcY0LfuJz76uiHgP4AZKxa5c',
    appId: '1:18254104624:web:52f27757a72811298605f5',
    messagingSenderId: '18254104624',
    projectId: 'db-todo-app-list',
    authDomain: 'db-todo-app-list.firebaseapp.com',
    storageBucket: 'db-todo-app-list.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgPq8ykuuG3yLB1ctTRPG7UIFPCpkEB1M',
    appId: '1:18254104624:android:39f37fc91da10bb18605f5',
    messagingSenderId: '18254104624',
    projectId: 'db-todo-app-list',
    storageBucket: 'db-todo-app-list.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCSK-GzE2QXfqtJQxgDXTK21sbjqM8fzc',
    appId: '1:18254104624:ios:9ed4435acb9883a58605f5',
    messagingSenderId: '18254104624',
    projectId: 'db-todo-app-list',
    storageBucket: 'db-todo-app-list.appspot.com',
    iosBundleId: 'com.example.todoAppList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCSK-GzE2QXfqtJQxgDXTK21sbjqM8fzc',
    appId: '1:18254104624:ios:7e0f4f0960d4d3f48605f5',
    messagingSenderId: '18254104624',
    projectId: 'db-todo-app-list',
    storageBucket: 'db-todo-app-list.appspot.com',
    iosBundleId: 'com.example.todoAppList.RunnerTests',
  );
}
